[package]
name = "users-service"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }


[lib]
path = "./lib.rs"

[[example]]
name = "users-service-alone"
path = "./examples/users-service-alone.rs"
