[tool.poetry]
name = "py-module"
version = "0.1.0"
description = ""
authors = ["TakiMoysha <mpwema782@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
maturin = "^1.4.0"


[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

