[package]
name = "drain-log"
version = "0.1.0"
edition = "2024"
description = "Take logs from pipeline or file and use drainlog for pattern matching."

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
crossterm = "0.29.0"
logdrain = "0.3"
ratatui = { version = "0.30.2", features = ["all-widgets", "crossterm"] }
thiserror = "2.0.20"
tokio = { version = "1.32.0", features = ["full"] }
