[package]
name = "simple-linux-widget"
version = "0.1.0"
edition = "2021"

[dependencies]
gio = "0.20.7"
gtk4 = "0.9.5"
glib = "0.20.7"
libc = "0.2.169"
clap = { version = "4.5.27", features = ["derive"] }
toml = "0.8.19"
serde = { version = "1.0.217", features = ["derive"] }
